# Generated by Django 3.2.8 on 2021-11-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('xs', models.IntegerField()),
                ('y', models.FloatField()),
                ('ys', models.IntegerField()),
                ('z', models.FloatField()),
                ('zs', models.IntegerField()),
                ('index', models.IntegerField()),
            ],
        ),
    ]
