# Generated by Django 3.2.8 on 2021-11-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='orientation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
