# Generated by Django 3.2.8 on 2021-11-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coordinates_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='id',
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
